### ISSUE TITLE
Cannot install hiclib package even after installation of mirnylab on OS X EI capitan

### ISSUE THREAD

**Issue by faustson** [XiaoTaoWang/HiC_pipeline#1]
Hi,
After I install all the required pacakges by <conda install numpy numexpr scipy ... gcc=4.8.5>, the mirnylab pacakge can be installed properly, however the hiclib can not be installed by <python setup.py install>.  It always shows error like this:
<..
binarySearch/fastBinSearch.cpp:1842:24:
binarySearch/mycode.h:4:6: error: 
error: command 'gcc' failed with exit status 1>

At first I even cannot install the mirnylab, but after change gcc to 4.8.5 (before I use 4.2.1 installed by Xcode), it works! Why gcc still can not compile for the hiclib? Do you have any suggestions? 
My OS is OS X EI capitan 10.11.6, python version is 2.7.13
Thank you in advance!

**Comment by XiaoTaoWang** [comment]
Have you tried ``python install_linux.py``?

**Comment by faustson** [comment]
This command seems OK, it shows as follow:
"

To skip checks use python install_linux.py --noCheck

Checking python version.. Correct!

Checking for mirnylib.. Found!

Checking for numpy.. Found!

Checking for numpy version.. Correct!

Checking for mirnylib.h5dict install.. H5dict test successful!

Checking for joblib.. Found!


The PYTHONPATH is already set in ~/.bash_profile

The PYTHONPATH is already set in ~/.bashrc

"

But I still can not import hiclib under python environment.

Thanks for your help!


Best,

Kun

**Comment by XiaoTaoWang** [comment]
You may need to close and re-open your terminal window to make the new environment variable settings take effect.

**Comment by faustson** [comment]
Actually I just directly copy the two folder "hiclib" and "hiclib.egg-info"
from src folder into my python lib path (../python2.7/site-packages/). It
seems work now!! I can go ahead to install the runHiC now. I will test some
example data to check whether runHiC could work well. Thanks!

**Comment by XiaoTaoWang** [comment]
Glad to hear that. The latest version of runHiC(0.7.0) is still in development and may contain bugs. Let me know if you have any further questions.
