### ISSUE TITLE
runHiC binning with user-defined resolutions

### ISSUE THREAD

**Issue by Brahmandam-Gayatri** [XiaoTaoWang/HiC_pipeline#18]
Hello XiaoTaoWang,

Thank you for the runHiC pipeline. For my analyses, I want to inspect the data at **15 kb and 20 kb** resolutions in addition to the resolutions binned when running runHiC default command. But I am encountering an error when I try to specify the mentioned resolutions. Is there a way to **bin at custom resolutions**?

Thanks,

Gayatri B.

**Comment by XiaoTaoWang** [comment]
Hi Gayatri, you can run runHiC with default parameters, and then use the cooler package to generate contact matrices at arbitrary resolutions as per your needs. This can be achieved by using the generated mcool file from runHiC as input. For example, if your mcool file is named "sample1.mcool", you can get the contact matrices at 15kb resolution using the following command:

    $ cooler coarsen -k 3 -p 4 -o sample1.15kb.cool sample1.mcool::resolutions/5000

**Comment by Brahmandam-Gayatri** [comment]
That worked, thanks a lot for resolving my query XiaoTaoWang! I am closing the issue, will come back if I cannot figure out anything else.

Regards,

Gayatri B.
